// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hotword.proto
// Protobuf C++ Version: 6.31.0

#include "hotword.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rero {

inline constexpr Result::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Result::Result(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Result_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResultDefaultTypeInternal() {}
  union {
    Result _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResultDefaultTypeInternal _Result_default_instance_;

inline constexpr RawEmbedding::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : embedding_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RawEmbedding::RawEmbedding(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RawEmbedding_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RawEmbeddingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RawEmbeddingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RawEmbeddingDefaultTypeInternal() {}
  union {
    RawEmbedding _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RawEmbeddingDefaultTypeInternal _RawEmbedding_default_instance_;

inline constexpr HotwordResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        hotword_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        confidence_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HotwordResult::HotwordResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HotwordResult_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HotwordResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HotwordResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HotwordResultDefaultTypeInternal() {}
  union {
    HotwordResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HotwordResultDefaultTypeInternal _HotwordResult_default_instance_;

inline constexpr HotwordFileName::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        hotword_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR HotwordFileName::HotwordFileName(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HotwordFileName_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HotwordFileNameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HotwordFileNameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HotwordFileNameDefaultTypeInternal() {}
  union {
    HotwordFileName _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HotwordFileNameDefaultTypeInternal _HotwordFileName_default_instance_;

inline constexpr HotwordEmbedding::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        hotword_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        embedding_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR HotwordEmbedding::HotwordEmbedding(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HotwordEmbedding_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HotwordEmbeddingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HotwordEmbeddingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HotwordEmbeddingDefaultTypeInternal() {}
  union {
    HotwordEmbedding _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HotwordEmbeddingDefaultTypeInternal _HotwordEmbedding_default_instance_;
}  // namespace rero
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_hotword_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_hotword_2eproto = nullptr;
const ::uint32_t
    TableStruct_hotword_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rero::HotwordResult, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rero::HotwordResult, _impl_.hotword_),
        PROTOBUF_FIELD_OFFSET(::rero::HotwordResult, _impl_.confidence_),
        0,
        1,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::rero::RawEmbedding, _impl_.embedding_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rero::HotwordEmbedding, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rero::HotwordEmbedding, _impl_.hotword_),
        PROTOBUF_FIELD_OFFSET(::rero::HotwordEmbedding, _impl_.embedding_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rero::Result, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rero::Result, _impl_.msg_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rero::HotwordFileName, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rero::HotwordFileName, _impl_.hotword_),
        PROTOBUF_FIELD_OFFSET(::rero::HotwordFileName, _impl_.filename_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::rero::HotwordResult)},
        {7, sizeof(::rero::RawEmbedding)},
        {9, sizeof(::rero::HotwordEmbedding)},
        {16, sizeof(::rero::Result)},
        {21, sizeof(::rero::HotwordFileName)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::rero::_HotwordResult_default_instance_._instance,
    &::rero::_RawEmbedding_default_instance_._instance,
    &::rero::_HotwordEmbedding_default_instance_._instance,
    &::rero::_Result_default_instance_._instance,
    &::rero::_HotwordFileName_default_instance_._instance,
};
const char descriptor_table_protodef_hotword_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rhotword.proto\022\004rero\032\013audio.proto\"4\n\rHo"
    "twordResult\022\017\n\007hotword\030\001 \001(\t\022\022\n\nconfiden"
    "ce\030\002 \001(\002\"!\n\014RawEmbedding\022\021\n\tembedding\030\001 "
    "\003(\002\"J\n\020HotwordEmbedding\022\017\n\007hotword\030\001 \001(\t"
    "\022%\n\tembedding\030\002 \001(\0132\022.rero.RawEmbedding\""
    "\025\n\006Result\022\013\n\003msg\030\001 \001(\t\"4\n\017HotwordFileNam"
    "e\022\017\n\007hotword\030\001 \001(\t\022\020\n\010filename\030\002 \001(\t2\271\002\n"
    "\020HotwordDetection\022<\n\022StartHotwordStream\022"
    "\013.rero.Audio\032\023.rero.HotwordResult\"\000(\0010\001\022"
    "8\n\020RecognizeHotword\022\013.rero.Audio\032\023.rero."
    "HotwordResult\"\000(\001\0223\n\014GetEmbedding\022\013.rero"
    ".Audio\032\022.rero.RawEmbedding\"\000(\001\022\?\n\025AddEmb"
    "eddingToHotword\022\026.rero.HotwordEmbedding\032"
    "\014.rero.Result\"\000\0227\n\016PersistHotword\022\025.rero"
    ".HotwordFileName\032\014.rero.Result\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_hotword_2eproto_deps[1] = {
        &::descriptor_table_audio_2eproto,
};
static ::absl::once_flag descriptor_table_hotword_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_hotword_2eproto = {
    false,
    false,
    600,
    descriptor_table_protodef_hotword_2eproto,
    "hotword.proto",
    &descriptor_table_hotword_2eproto_once,
    descriptor_table_hotword_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_hotword_2eproto::offsets,
    file_level_enum_descriptors_hotword_2eproto,
    file_level_service_descriptors_hotword_2eproto,
};
namespace rero {
// ===================================================================

class HotwordResult::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HotwordResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HotwordResult, _impl_._has_bits_);
};

HotwordResult::HotwordResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HotwordResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rero.HotwordResult)
}
PROTOBUF_NDEBUG_INLINE HotwordResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::rero::HotwordResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        hotword_(arena, from.hotword_) {}

HotwordResult::HotwordResult(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const HotwordResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HotwordResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HotwordResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.confidence_ = from._impl_.confidence_;

  // @@protoc_insertion_point(copy_constructor:rero.HotwordResult)
}
PROTOBUF_NDEBUG_INLINE HotwordResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        hotword_(arena) {}

inline void HotwordResult::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.confidence_ = {};
}
HotwordResult::~HotwordResult() {
  // @@protoc_insertion_point(destructor:rero.HotwordResult)
  SharedDtor(*this);
}
inline void HotwordResult::SharedDtor(MessageLite& self) {
  HotwordResult& this_ = static_cast<HotwordResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.hotword_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HotwordResult::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HotwordResult(arena);
}
constexpr auto HotwordResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(HotwordResult),
                                            alignof(HotwordResult));
}
constexpr auto HotwordResult::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HotwordResult_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HotwordResult::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HotwordResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HotwordResult::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HotwordResult>(), &HotwordResult::ByteSizeLong,
              &HotwordResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HotwordResult, _impl_._cached_size_),
          false,
      },
      &HotwordResult::kDescriptorMethods,
      &descriptor_table_hotword_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HotwordResult_class_data_ =
        HotwordResult::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HotwordResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HotwordResult_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HotwordResult_class_data_.tc_table);
  return HotwordResult_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 34, 2>
HotwordResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HotwordResult, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HotwordResult_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rero::HotwordResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float confidence = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(HotwordResult, _impl_.confidence_)}},
    // string hotword = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(HotwordResult, _impl_.hotword_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string hotword = 1;
    {PROTOBUF_FIELD_OFFSET(HotwordResult, _impl_.hotword_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float confidence = 2;
    {PROTOBUF_FIELD_OFFSET(HotwordResult, _impl_.confidence_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
    "\22\7\0\0\0\0\0\0"
    "rero.HotwordResult"
    "hotword"
  }},
};
PROTOBUF_NOINLINE void HotwordResult::Clear() {
// @@protoc_insertion_point(message_clear_start:rero.HotwordResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.hotword_.ClearNonDefaultToEmpty();
  }
  _impl_.confidence_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HotwordResult::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HotwordResult& this_ = static_cast<const HotwordResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HotwordResult::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HotwordResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:rero.HotwordResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string hotword = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_hotword().empty()) {
      const ::std::string& _s = this_._internal_hotword();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.HotwordResult.hotword");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // float confidence = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_confidence(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rero.HotwordResult)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HotwordResult::ByteSizeLong(const MessageLite& base) {
  const HotwordResult& this_ = static_cast<const HotwordResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HotwordResult::ByteSizeLong() const {
  const HotwordResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rero.HotwordResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string hotword = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_hotword().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_hotword());
      }
    }
    // float confidence = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HotwordResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HotwordResult*>(&to_msg);
  auto& from = static_cast<const HotwordResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rero.HotwordResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_hotword().empty()) {
        _this->_internal_set_hotword(from._internal_hotword());
      } else {
        if (_this->_impl_.hotword_.IsDefault()) {
          _this->_internal_set_hotword("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_confidence()) != 0) {
        _this->_impl_.confidence_ = from._impl_.confidence_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HotwordResult::CopyFrom(const HotwordResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rero.HotwordResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HotwordResult::InternalSwap(HotwordResult* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hotword_, &other->_impl_.hotword_, arena);
  swap(_impl_.confidence_, other->_impl_.confidence_);
}

::google::protobuf::Metadata HotwordResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RawEmbedding::_Internal {
 public:
};

RawEmbedding::RawEmbedding(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RawEmbedding_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rero.RawEmbedding)
}
PROTOBUF_NDEBUG_INLINE RawEmbedding::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::rero::RawEmbedding& from_msg)
      : embedding_{visibility, arena, from.embedding_},
        _cached_size_{0} {}

RawEmbedding::RawEmbedding(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RawEmbedding& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RawEmbedding_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RawEmbedding* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rero.RawEmbedding)
}
PROTOBUF_NDEBUG_INLINE RawEmbedding::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : embedding_{visibility, arena},
        _cached_size_{0} {}

inline void RawEmbedding::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RawEmbedding::~RawEmbedding() {
  // @@protoc_insertion_point(destructor:rero.RawEmbedding)
  SharedDtor(*this);
}
inline void RawEmbedding::SharedDtor(MessageLite& self) {
  RawEmbedding& this_ = static_cast<RawEmbedding&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RawEmbedding::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RawEmbedding(arena);
}
constexpr auto RawEmbedding::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(RawEmbedding, _impl_.embedding_) +
          decltype(RawEmbedding::_impl_.embedding_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(RawEmbedding), alignof(RawEmbedding), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&RawEmbedding::PlacementNew_,
                                 sizeof(RawEmbedding),
                                 alignof(RawEmbedding));
  }
}
constexpr auto RawEmbedding::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RawEmbedding_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RawEmbedding::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RawEmbedding>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RawEmbedding::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RawEmbedding>(), &RawEmbedding::ByteSizeLong,
              &RawEmbedding::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RawEmbedding, _impl_._cached_size_),
          false,
      },
      &RawEmbedding::kDescriptorMethods,
      &descriptor_table_hotword_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RawEmbedding_class_data_ =
        RawEmbedding::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RawEmbedding::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RawEmbedding_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RawEmbedding_class_data_.tc_table);
  return RawEmbedding_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
RawEmbedding::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RawEmbedding_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rero::RawEmbedding>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float embedding = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RawEmbedding, _impl_.embedding_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float embedding = 1;
    {PROTOBUF_FIELD_OFFSET(RawEmbedding, _impl_.embedding_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RawEmbedding::Clear() {
// @@protoc_insertion_point(message_clear_start:rero.RawEmbedding)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.embedding_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RawEmbedding::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RawEmbedding& this_ = static_cast<const RawEmbedding&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RawEmbedding::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RawEmbedding& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:rero.RawEmbedding)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float embedding = 1;
  if (this_._internal_embedding_size() > 0) {
    target = stream->WriteFixedPacked(1, this_._internal_embedding(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rero.RawEmbedding)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RawEmbedding::ByteSizeLong(const MessageLite& base) {
  const RawEmbedding& this_ = static_cast<const RawEmbedding&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RawEmbedding::ByteSizeLong() const {
  const RawEmbedding& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rero.RawEmbedding)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated float embedding = 1;
    {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_embedding_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RawEmbedding::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RawEmbedding*>(&to_msg);
  auto& from = static_cast<const RawEmbedding&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rero.RawEmbedding)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_embedding()->MergeFrom(from._internal_embedding());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RawEmbedding::CopyFrom(const RawEmbedding& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rero.RawEmbedding)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RawEmbedding::InternalSwap(RawEmbedding* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.embedding_.InternalSwap(&other->_impl_.embedding_);
}

::google::protobuf::Metadata RawEmbedding::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HotwordEmbedding::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HotwordEmbedding>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HotwordEmbedding, _impl_._has_bits_);
};

HotwordEmbedding::HotwordEmbedding(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HotwordEmbedding_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rero.HotwordEmbedding)
}
PROTOBUF_NDEBUG_INLINE HotwordEmbedding::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::rero::HotwordEmbedding& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        hotword_(arena, from.hotword_) {}

HotwordEmbedding::HotwordEmbedding(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const HotwordEmbedding& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HotwordEmbedding_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HotwordEmbedding* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.embedding_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.embedding_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:rero.HotwordEmbedding)
}
PROTOBUF_NDEBUG_INLINE HotwordEmbedding::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        hotword_(arena) {}

inline void HotwordEmbedding::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.embedding_ = {};
}
HotwordEmbedding::~HotwordEmbedding() {
  // @@protoc_insertion_point(destructor:rero.HotwordEmbedding)
  SharedDtor(*this);
}
inline void HotwordEmbedding::SharedDtor(MessageLite& self) {
  HotwordEmbedding& this_ = static_cast<HotwordEmbedding&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.hotword_.Destroy();
  delete this_._impl_.embedding_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HotwordEmbedding::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HotwordEmbedding(arena);
}
constexpr auto HotwordEmbedding::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(HotwordEmbedding),
                                            alignof(HotwordEmbedding));
}
constexpr auto HotwordEmbedding::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HotwordEmbedding_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HotwordEmbedding::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HotwordEmbedding>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HotwordEmbedding::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HotwordEmbedding>(), &HotwordEmbedding::ByteSizeLong,
              &HotwordEmbedding::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HotwordEmbedding, _impl_._cached_size_),
          false,
      },
      &HotwordEmbedding::kDescriptorMethods,
      &descriptor_table_hotword_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HotwordEmbedding_class_data_ =
        HotwordEmbedding::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HotwordEmbedding::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HotwordEmbedding_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HotwordEmbedding_class_data_.tc_table);
  return HotwordEmbedding_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 37, 2>
HotwordEmbedding::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HotwordEmbedding, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    HotwordEmbedding_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rero::HotwordEmbedding>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .rero.RawEmbedding embedding = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(HotwordEmbedding, _impl_.embedding_)}},
    // string hotword = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(HotwordEmbedding, _impl_.hotword_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string hotword = 1;
    {PROTOBUF_FIELD_OFFSET(HotwordEmbedding, _impl_.hotword_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .rero.RawEmbedding embedding = 2;
    {PROTOBUF_FIELD_OFFSET(HotwordEmbedding, _impl_.embedding_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::rero::RawEmbedding>()},
  }},
  {{
    "\25\7\0\0\0\0\0\0"
    "rero.HotwordEmbedding"
    "hotword"
  }},
};
PROTOBUF_NOINLINE void HotwordEmbedding::Clear() {
// @@protoc_insertion_point(message_clear_start:rero.HotwordEmbedding)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.hotword_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.embedding_ != nullptr);
      _impl_.embedding_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HotwordEmbedding::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HotwordEmbedding& this_ = static_cast<const HotwordEmbedding&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HotwordEmbedding::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HotwordEmbedding& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:rero.HotwordEmbedding)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string hotword = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_hotword().empty()) {
      const ::std::string& _s = this_._internal_hotword();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.HotwordEmbedding.hotword");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // .rero.RawEmbedding embedding = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.embedding_, this_._impl_.embedding_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rero.HotwordEmbedding)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HotwordEmbedding::ByteSizeLong(const MessageLite& base) {
  const HotwordEmbedding& this_ = static_cast<const HotwordEmbedding&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HotwordEmbedding::ByteSizeLong() const {
  const HotwordEmbedding& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rero.HotwordEmbedding)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string hotword = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_hotword().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_hotword());
      }
    }
    // .rero.RawEmbedding embedding = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.embedding_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HotwordEmbedding::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HotwordEmbedding*>(&to_msg);
  auto& from = static_cast<const HotwordEmbedding&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rero.HotwordEmbedding)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_hotword().empty()) {
        _this->_internal_set_hotword(from._internal_hotword());
      } else {
        if (_this->_impl_.hotword_.IsDefault()) {
          _this->_internal_set_hotword("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.embedding_ != nullptr);
      if (_this->_impl_.embedding_ == nullptr) {
        _this->_impl_.embedding_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.embedding_);
      } else {
        _this->_impl_.embedding_->MergeFrom(*from._impl_.embedding_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HotwordEmbedding::CopyFrom(const HotwordEmbedding& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rero.HotwordEmbedding)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HotwordEmbedding::InternalSwap(HotwordEmbedding* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hotword_, &other->_impl_.hotword_, arena);
  swap(_impl_.embedding_, other->_impl_.embedding_);
}

::google::protobuf::Metadata HotwordEmbedding::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Result::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Result>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Result, _impl_._has_bits_);
};

Result::Result(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Result_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rero.Result)
}
PROTOBUF_NDEBUG_INLINE Result::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::rero::Result& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        msg_(arena, from.msg_) {}

Result::Result(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Result& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Result_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Result* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rero.Result)
}
PROTOBUF_NDEBUG_INLINE Result::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        msg_(arena) {}

inline void Result::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Result::~Result() {
  // @@protoc_insertion_point(destructor:rero.Result)
  SharedDtor(*this);
}
inline void Result::SharedDtor(MessageLite& self) {
  Result& this_ = static_cast<Result&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Result::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Result(arena);
}
constexpr auto Result::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Result),
                                            alignof(Result));
}
constexpr auto Result::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Result_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Result::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Result>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Result::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Result>(), &Result::ByteSizeLong,
              &Result::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Result, _impl_._cached_size_),
          false,
      },
      &Result::kDescriptorMethods,
      &descriptor_table_hotword_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Result_class_data_ =
        Result::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Result::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Result_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Result_class_data_.tc_table);
  return Result_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 23, 2>
Result::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Result, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Result_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rero::Result>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string msg = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Result, _impl_.msg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string msg = 1;
    {PROTOBUF_FIELD_OFFSET(Result, _impl_.msg_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\13\3\0\0\0\0\0\0"
    "rero.Result"
    "msg"
  }},
};
PROTOBUF_NOINLINE void Result::Clear() {
// @@protoc_insertion_point(message_clear_start:rero.Result)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.msg_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Result::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Result& this_ = static_cast<const Result&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Result::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Result& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:rero.Result)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string msg = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_msg().empty()) {
      const ::std::string& _s = this_._internal_msg();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.Result.msg");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rero.Result)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Result::ByteSizeLong(const MessageLite& base) {
  const Result& this_ = static_cast<const Result&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Result::ByteSizeLong() const {
  const Result& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rero.Result)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string msg = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_msg().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_msg());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Result::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Result*>(&to_msg);
  auto& from = static_cast<const Result&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rero.Result)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_msg().empty()) {
      _this->_internal_set_msg(from._internal_msg());
    } else {
      if (_this->_impl_.msg_.IsDefault()) {
        _this->_internal_set_msg("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Result::CopyFrom(const Result& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rero.Result)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Result::InternalSwap(Result* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
}

::google::protobuf::Metadata Result::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HotwordFileName::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HotwordFileName>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HotwordFileName, _impl_._has_bits_);
};

HotwordFileName::HotwordFileName(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HotwordFileName_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rero.HotwordFileName)
}
PROTOBUF_NDEBUG_INLINE HotwordFileName::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::rero::HotwordFileName& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        hotword_(arena, from.hotword_),
        filename_(arena, from.filename_) {}

HotwordFileName::HotwordFileName(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const HotwordFileName& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HotwordFileName_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HotwordFileName* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rero.HotwordFileName)
}
PROTOBUF_NDEBUG_INLINE HotwordFileName::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        hotword_(arena),
        filename_(arena) {}

inline void HotwordFileName::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
HotwordFileName::~HotwordFileName() {
  // @@protoc_insertion_point(destructor:rero.HotwordFileName)
  SharedDtor(*this);
}
inline void HotwordFileName::SharedDtor(MessageLite& self) {
  HotwordFileName& this_ = static_cast<HotwordFileName&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.hotword_.Destroy();
  this_._impl_.filename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HotwordFileName::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HotwordFileName(arena);
}
constexpr auto HotwordFileName::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(HotwordFileName),
                                            alignof(HotwordFileName));
}
constexpr auto HotwordFileName::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HotwordFileName_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HotwordFileName::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HotwordFileName>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HotwordFileName::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HotwordFileName>(), &HotwordFileName::ByteSizeLong,
              &HotwordFileName::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HotwordFileName, _impl_._cached_size_),
          false,
      },
      &HotwordFileName::kDescriptorMethods,
      &descriptor_table_hotword_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HotwordFileName_class_data_ =
        HotwordFileName::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HotwordFileName::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HotwordFileName_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HotwordFileName_class_data_.tc_table);
  return HotwordFileName_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2>
HotwordFileName::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HotwordFileName, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HotwordFileName_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rero::HotwordFileName>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string filename = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(HotwordFileName, _impl_.filename_)}},
    // string hotword = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(HotwordFileName, _impl_.hotword_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string hotword = 1;
    {PROTOBUF_FIELD_OFFSET(HotwordFileName, _impl_.hotword_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string filename = 2;
    {PROTOBUF_FIELD_OFFSET(HotwordFileName, _impl_.filename_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\7\10\0\0\0\0\0"
    "rero.HotwordFileName"
    "hotword"
    "filename"
  }},
};
PROTOBUF_NOINLINE void HotwordFileName::Clear() {
// @@protoc_insertion_point(message_clear_start:rero.HotwordFileName)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.hotword_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.filename_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HotwordFileName::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HotwordFileName& this_ = static_cast<const HotwordFileName&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HotwordFileName::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HotwordFileName& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:rero.HotwordFileName)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string hotword = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_hotword().empty()) {
      const ::std::string& _s = this_._internal_hotword();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.HotwordFileName.hotword");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string filename = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_filename().empty()) {
      const ::std::string& _s = this_._internal_filename();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.HotwordFileName.filename");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rero.HotwordFileName)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HotwordFileName::ByteSizeLong(const MessageLite& base) {
  const HotwordFileName& this_ = static_cast<const HotwordFileName&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HotwordFileName::ByteSizeLong() const {
  const HotwordFileName& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rero.HotwordFileName)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string hotword = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_hotword().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_hotword());
      }
    }
    // string filename = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_filename().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_filename());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HotwordFileName::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HotwordFileName*>(&to_msg);
  auto& from = static_cast<const HotwordFileName&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rero.HotwordFileName)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_hotword().empty()) {
        _this->_internal_set_hotword(from._internal_hotword());
      } else {
        if (_this->_impl_.hotword_.IsDefault()) {
          _this->_internal_set_hotword("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_filename().empty()) {
        _this->_internal_set_filename(from._internal_filename());
      } else {
        if (_this->_impl_.filename_.IsDefault()) {
          _this->_internal_set_filename("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HotwordFileName::CopyFrom(const HotwordFileName& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rero.HotwordFileName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HotwordFileName::InternalSwap(HotwordFileName* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hotword_, &other->_impl_.hotword_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
}

::google::protobuf::Metadata HotwordFileName::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rero
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_hotword_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
