// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nlu.proto
// Protobuf C++ Version: 6.31.0

#include "nlu.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rero {

inline constexpr Slot::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        rawvalue_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        entity_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        slotname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rangestart_{0u},
        rangeend_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Slot::Slot(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Slot_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SlotDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SlotDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SlotDefaultTypeInternal() {}
  union {
    Slot _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SlotDefaultTypeInternal _Slot_default_instance_;

inline constexpr NLURequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        request_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR NLURequest::NLURequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NLURequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NLURequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NLURequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NLURequestDefaultTypeInternal() {}
  union {
    NLURequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NLURequestDefaultTypeInternal _NLURequest_default_instance_;

inline constexpr Intent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        slots_{},
        inputtext_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        intentname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        probability_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Intent::Intent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Intent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct IntentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IntentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IntentDefaultTypeInternal() {}
  union {
    Intent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IntentDefaultTypeInternal _Intent_default_instance_;
}  // namespace rero
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_nlu_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_nlu_2eproto = nullptr;
const ::uint32_t
    TableStruct_nlu_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rero::NLURequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rero::NLURequest, _impl_.request_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rero::Intent, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rero::Intent, _impl_.inputtext_),
        PROTOBUF_FIELD_OFFSET(::rero::Intent, _impl_.intentname_),
        PROTOBUF_FIELD_OFFSET(::rero::Intent, _impl_.probability_),
        PROTOBUF_FIELD_OFFSET(::rero::Intent, _impl_.slots_),
        0,
        1,
        2,
        ~0u,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rero::Slot, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rero::Slot, _impl_.rawvalue_),
        PROTOBUF_FIELD_OFFSET(::rero::Slot, _impl_.entity_),
        PROTOBUF_FIELD_OFFSET(::rero::Slot, _impl_.slotname_),
        PROTOBUF_FIELD_OFFSET(::rero::Slot, _impl_.rangestart_),
        PROTOBUF_FIELD_OFFSET(::rero::Slot, _impl_.rangeend_),
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::rero::NLURequest)},
        {5, sizeof(::rero::Intent)},
        {16, sizeof(::rero::Slot)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::rero::_NLURequest_default_instance_._instance,
    &::rero::_Intent_default_instance_._instance,
    &::rero::_Slot_default_instance_._instance,
};
const char descriptor_table_protodef_nlu_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tnlu.proto\022\004rero\"\035\n\nNLURequest\022\017\n\007reque"
    "st\030\001 \001(\t\"_\n\006Intent\022\021\n\tinputText\030\001 \001(\t\022\022\n"
    "\nintentName\030\002 \001(\t\022\023\n\013probability\030\003 \001(\002\022\031"
    "\n\005slots\030\004 \003(\0132\n.rero.Slot\"`\n\004Slot\022\020\n\010raw"
    "Value\030\001 \001(\t\022\016\n\006entity\030\002 \001(\t\022\020\n\010slotName\030"
    "\003 \001(\t\022\022\n\nrangeStart\030\004 \001(\r\022\020\n\010rangeEnd\030\005 "
    "\001(\r2:\n\003NLU\0223\n\017GetSpeechIntent\022\020.rero.NLU"
    "Request\032\014.rero.Intent\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_nlu_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nlu_2eproto = {
    false,
    false,
    311,
    descriptor_table_protodef_nlu_2eproto,
    "nlu.proto",
    &descriptor_table_nlu_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_nlu_2eproto::offsets,
    file_level_enum_descriptors_nlu_2eproto,
    file_level_service_descriptors_nlu_2eproto,
};
namespace rero {
// ===================================================================

class NLURequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NLURequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NLURequest, _impl_._has_bits_);
};

NLURequest::NLURequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NLURequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rero.NLURequest)
}
PROTOBUF_NDEBUG_INLINE NLURequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::rero::NLURequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        request_(arena, from.request_) {}

NLURequest::NLURequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NLURequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NLURequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NLURequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rero.NLURequest)
}
PROTOBUF_NDEBUG_INLINE NLURequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        request_(arena) {}

inline void NLURequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NLURequest::~NLURequest() {
  // @@protoc_insertion_point(destructor:rero.NLURequest)
  SharedDtor(*this);
}
inline void NLURequest::SharedDtor(MessageLite& self) {
  NLURequest& this_ = static_cast<NLURequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.request_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NLURequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NLURequest(arena);
}
constexpr auto NLURequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NLURequest),
                                            alignof(NLURequest));
}
constexpr auto NLURequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NLURequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NLURequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NLURequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NLURequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NLURequest>(), &NLURequest::ByteSizeLong,
              &NLURequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NLURequest, _impl_._cached_size_),
          false,
      },
      &NLURequest::kDescriptorMethods,
      &descriptor_table_nlu_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NLURequest_class_data_ =
        NLURequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NLURequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NLURequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NLURequest_class_data_.tc_table);
  return NLURequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 31, 2>
NLURequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NLURequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NLURequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rero::NLURequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string request = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(NLURequest, _impl_.request_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string request = 1;
    {PROTOBUF_FIELD_OFFSET(NLURequest, _impl_.request_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\7\0\0\0\0\0\0"
    "rero.NLURequest"
    "request"
  }},
};
PROTOBUF_NOINLINE void NLURequest::Clear() {
// @@protoc_insertion_point(message_clear_start:rero.NLURequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.request_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NLURequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NLURequest& this_ = static_cast<const NLURequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NLURequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NLURequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:rero.NLURequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string request = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_request().empty()) {
      const ::std::string& _s = this_._internal_request();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.NLURequest.request");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rero.NLURequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NLURequest::ByteSizeLong(const MessageLite& base) {
  const NLURequest& this_ = static_cast<const NLURequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NLURequest::ByteSizeLong() const {
  const NLURequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rero.NLURequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string request = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_request().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_request());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NLURequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NLURequest*>(&to_msg);
  auto& from = static_cast<const NLURequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rero.NLURequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_request().empty()) {
      _this->_internal_set_request(from._internal_request());
    } else {
      if (_this->_impl_.request_.IsDefault()) {
        _this->_internal_set_request("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NLURequest::CopyFrom(const NLURequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rero.NLURequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NLURequest::InternalSwap(NLURequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.request_, &other->_impl_.request_, arena);
}

::google::protobuf::Metadata NLURequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Intent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Intent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Intent, _impl_._has_bits_);
};

Intent::Intent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Intent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rero.Intent)
}
PROTOBUF_NDEBUG_INLINE Intent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::rero::Intent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        slots_{visibility, arena, from.slots_},
        inputtext_(arena, from.inputtext_),
        intentname_(arena, from.intentname_) {}

Intent::Intent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Intent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Intent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Intent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.probability_ = from._impl_.probability_;

  // @@protoc_insertion_point(copy_constructor:rero.Intent)
}
PROTOBUF_NDEBUG_INLINE Intent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        slots_{visibility, arena},
        inputtext_(arena),
        intentname_(arena) {}

inline void Intent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.probability_ = {};
}
Intent::~Intent() {
  // @@protoc_insertion_point(destructor:rero.Intent)
  SharedDtor(*this);
}
inline void Intent::SharedDtor(MessageLite& self) {
  Intent& this_ = static_cast<Intent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.inputtext_.Destroy();
  this_._impl_.intentname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Intent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Intent(arena);
}
constexpr auto Intent::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Intent, _impl_.slots_) +
          decltype(Intent::_impl_.slots_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Intent), alignof(Intent), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Intent::PlacementNew_,
                                 sizeof(Intent),
                                 alignof(Intent));
  }
}
constexpr auto Intent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Intent_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Intent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Intent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Intent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Intent>(), &Intent::ByteSizeLong,
              &Intent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Intent, _impl_._cached_size_),
          false,
      },
      &Intent::kDescriptorMethods,
      &descriptor_table_nlu_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Intent_class_data_ =
        Intent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Intent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Intent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Intent_class_data_.tc_table);
  return Intent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 39, 2>
Intent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Intent, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Intent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rero::Intent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .rero.Slot slots = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Intent, _impl_.slots_)}},
    // string inputText = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Intent, _impl_.inputtext_)}},
    // string intentName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(Intent, _impl_.intentname_)}},
    // float probability = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(Intent, _impl_.probability_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string inputText = 1;
    {PROTOBUF_FIELD_OFFSET(Intent, _impl_.inputtext_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string intentName = 2;
    {PROTOBUF_FIELD_OFFSET(Intent, _impl_.intentname_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float probability = 3;
    {PROTOBUF_FIELD_OFFSET(Intent, _impl_.probability_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // repeated .rero.Slot slots = 4;
    {PROTOBUF_FIELD_OFFSET(Intent, _impl_.slots_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::rero::Slot>()},
  }},
  {{
    "\13\11\12\0\0\0\0\0"
    "rero.Intent"
    "inputText"
    "intentName"
  }},
};
PROTOBUF_NOINLINE void Intent::Clear() {
// @@protoc_insertion_point(message_clear_start:rero.Intent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.slots_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.inputtext_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.intentname_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.probability_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Intent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Intent& this_ = static_cast<const Intent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Intent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Intent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:rero.Intent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string inputText = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_inputtext().empty()) {
      const ::std::string& _s = this_._internal_inputtext();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.Intent.inputText");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string intentName = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_intentname().empty()) {
      const ::std::string& _s = this_._internal_intentname();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.Intent.intentName");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // float probability = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_probability()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          3, this_._internal_probability(), target);
    }
  }

  // repeated .rero.Slot slots = 4;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_slots_size());
       i < n; i++) {
    const auto& repfield = this_._internal_slots().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            4, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rero.Intent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Intent::ByteSizeLong(const MessageLite& base) {
  const Intent& this_ = static_cast<const Intent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Intent::ByteSizeLong() const {
  const Intent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rero.Intent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .rero.Slot slots = 4;
    {
      total_size += 1UL * this_._internal_slots_size();
      for (const auto& msg : this_._internal_slots()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // string inputText = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_inputtext().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_inputtext());
      }
    }
    // string intentName = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_intentname().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_intentname());
      }
    }
    // float probability = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_probability()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Intent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Intent*>(&to_msg);
  auto& from = static_cast<const Intent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rero.Intent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_slots()->MergeFrom(
      from._internal_slots());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_inputtext().empty()) {
        _this->_internal_set_inputtext(from._internal_inputtext());
      } else {
        if (_this->_impl_.inputtext_.IsDefault()) {
          _this->_internal_set_inputtext("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_intentname().empty()) {
        _this->_internal_set_intentname(from._internal_intentname());
      } else {
        if (_this->_impl_.intentname_.IsDefault()) {
          _this->_internal_set_intentname("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_probability()) != 0) {
        _this->_impl_.probability_ = from._impl_.probability_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Intent::CopyFrom(const Intent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rero.Intent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Intent::InternalSwap(Intent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.slots_.InternalSwap(&other->_impl_.slots_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.inputtext_, &other->_impl_.inputtext_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.intentname_, &other->_impl_.intentname_, arena);
  swap(_impl_.probability_, other->_impl_.probability_);
}

::google::protobuf::Metadata Intent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Slot::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Slot>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Slot, _impl_._has_bits_);
};

Slot::Slot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Slot_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rero.Slot)
}
PROTOBUF_NDEBUG_INLINE Slot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::rero::Slot& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        rawvalue_(arena, from.rawvalue_),
        entity_(arena, from.entity_),
        slotname_(arena, from.slotname_) {}

Slot::Slot(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Slot& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Slot_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Slot* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, rangestart_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, rangestart_),
           offsetof(Impl_, rangeend_) -
               offsetof(Impl_, rangestart_) +
               sizeof(Impl_::rangeend_));

  // @@protoc_insertion_point(copy_constructor:rero.Slot)
}
PROTOBUF_NDEBUG_INLINE Slot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        rawvalue_(arena),
        entity_(arena),
        slotname_(arena) {}

inline void Slot::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, rangestart_),
           0,
           offsetof(Impl_, rangeend_) -
               offsetof(Impl_, rangestart_) +
               sizeof(Impl_::rangeend_));
}
Slot::~Slot() {
  // @@protoc_insertion_point(destructor:rero.Slot)
  SharedDtor(*this);
}
inline void Slot::SharedDtor(MessageLite& self) {
  Slot& this_ = static_cast<Slot&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.rawvalue_.Destroy();
  this_._impl_.entity_.Destroy();
  this_._impl_.slotname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Slot::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Slot(arena);
}
constexpr auto Slot::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Slot),
                                            alignof(Slot));
}
constexpr auto Slot::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Slot_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Slot::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Slot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Slot::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Slot>(), &Slot::ByteSizeLong,
              &Slot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Slot, _impl_._cached_size_),
          false,
      },
      &Slot::kDescriptorMethods,
      &descriptor_table_nlu_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Slot_class_data_ =
        Slot::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Slot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Slot_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Slot_class_data_.tc_table);
  return Slot_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 40, 2>
Slot::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Slot, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Slot_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rero::Slot>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string rawValue = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Slot, _impl_.rawvalue_)}},
    // string entity = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(Slot, _impl_.entity_)}},
    // string slotName = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(Slot, _impl_.slotname_)}},
    // uint32 rangeStart = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Slot, _impl_.rangestart_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(Slot, _impl_.rangestart_)}},
    // uint32 rangeEnd = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Slot, _impl_.rangeend_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(Slot, _impl_.rangeend_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string rawValue = 1;
    {PROTOBUF_FIELD_OFFSET(Slot, _impl_.rawvalue_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string entity = 2;
    {PROTOBUF_FIELD_OFFSET(Slot, _impl_.entity_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string slotName = 3;
    {PROTOBUF_FIELD_OFFSET(Slot, _impl_.slotname_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 rangeStart = 4;
    {PROTOBUF_FIELD_OFFSET(Slot, _impl_.rangestart_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 rangeEnd = 5;
    {PROTOBUF_FIELD_OFFSET(Slot, _impl_.rangeend_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\11\10\6\10\0\0\0\0"
    "rero.Slot"
    "rawValue"
    "entity"
    "slotName"
  }},
};
PROTOBUF_NOINLINE void Slot::Clear() {
// @@protoc_insertion_point(message_clear_start:rero.Slot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.rawvalue_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.entity_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.slotname_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x00000018u) != 0) {
    ::memset(&_impl_.rangestart_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.rangeend_) -
        reinterpret_cast<char*>(&_impl_.rangestart_)) + sizeof(_impl_.rangeend_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Slot::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Slot& this_ = static_cast<const Slot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Slot::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Slot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:rero.Slot)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string rawValue = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_rawvalue().empty()) {
      const ::std::string& _s = this_._internal_rawvalue();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.Slot.rawValue");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string entity = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_entity().empty()) {
      const ::std::string& _s = this_._internal_entity();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.Slot.entity");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string slotName = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (!this_._internal_slotname().empty()) {
      const ::std::string& _s = this_._internal_slotname();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rero.Slot.slotName");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // uint32 rangeStart = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (this_._internal_rangestart() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          4, this_._internal_rangestart(), target);
    }
  }

  // uint32 rangeEnd = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (this_._internal_rangeend() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_rangeend(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rero.Slot)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Slot::ByteSizeLong(const MessageLite& base) {
  const Slot& this_ = static_cast<const Slot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Slot::ByteSizeLong() const {
  const Slot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rero.Slot)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // string rawValue = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_rawvalue().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_rawvalue());
      }
    }
    // string entity = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_entity().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_entity());
      }
    }
    // string slotName = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!this_._internal_slotname().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_slotname());
      }
    }
    // uint32 rangeStart = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (this_._internal_rangestart() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_rangestart());
      }
    }
    // uint32 rangeEnd = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (this_._internal_rangeend() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_rangeend());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Slot::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Slot*>(&to_msg);
  auto& from = static_cast<const Slot&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rero.Slot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_rawvalue().empty()) {
        _this->_internal_set_rawvalue(from._internal_rawvalue());
      } else {
        if (_this->_impl_.rawvalue_.IsDefault()) {
          _this->_internal_set_rawvalue("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_entity().empty()) {
        _this->_internal_set_entity(from._internal_entity());
      } else {
        if (_this->_impl_.entity_.IsDefault()) {
          _this->_internal_set_entity("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!from._internal_slotname().empty()) {
        _this->_internal_set_slotname(from._internal_slotname());
      } else {
        if (_this->_impl_.slotname_.IsDefault()) {
          _this->_internal_set_slotname("");
        }
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (from._internal_rangestart() != 0) {
        _this->_impl_.rangestart_ = from._impl_.rangestart_;
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (from._internal_rangeend() != 0) {
        _this->_impl_.rangeend_ = from._impl_.rangeend_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Slot::CopyFrom(const Slot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rero.Slot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Slot::InternalSwap(Slot* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rawvalue_, &other->_impl_.rawvalue_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.entity_, &other->_impl_.entity_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.slotname_, &other->_impl_.slotname_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Slot, _impl_.rangeend_)
      + sizeof(Slot::_impl_.rangeend_)
      - PROTOBUF_FIELD_OFFSET(Slot, _impl_.rangestart_)>(
          reinterpret_cast<char*>(&_impl_.rangestart_),
          reinterpret_cast<char*>(&other->_impl_.rangestart_));
}

::google::protobuf::Metadata Slot::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rero
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_nlu_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
